package com.gabrielittner.threetenbp;

import java.lang.IllegalArgumentException;
import java.lang.String;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

class LazyZoneRules {
  static final String VERSION = "2017b";

  static final Set<String> REGION_IDS;

  static {
    Set<String> ids = new LinkedHashSet<>(587);
    ids.add("Africa/Abidjan");
    ids.add("Africa/Accra");
    ids.add("Africa/Addis_Ababa");
    ids.add("Africa/Algiers");
    ids.add("Africa/Asmara");
    ids.add("Africa/Asmera");
    ids.add("Africa/Bamako");
    ids.add("Africa/Bangui");
    ids.add("Africa/Banjul");
    ids.add("Africa/Bissau");
    ids.add("Africa/Blantyre");
    ids.add("Africa/Brazzaville");
    ids.add("Africa/Bujumbura");
    ids.add("Africa/Cairo");
    ids.add("Africa/Casablanca");
    ids.add("Africa/Ceuta");
    ids.add("Africa/Conakry");
    ids.add("Africa/Dakar");
    ids.add("Africa/Dar_es_Salaam");
    ids.add("Africa/Djibouti");
    ids.add("Africa/Douala");
    ids.add("Africa/El_Aaiun");
    ids.add("Africa/Freetown");
    ids.add("Africa/Gaborone");
    ids.add("Africa/Harare");
    ids.add("Africa/Johannesburg");
    ids.add("Africa/Juba");
    ids.add("Africa/Kampala");
    ids.add("Africa/Khartoum");
    ids.add("Africa/Kigali");
    ids.add("Africa/Kinshasa");
    ids.add("Africa/Lagos");
    ids.add("Africa/Libreville");
    ids.add("Africa/Lome");
    ids.add("Africa/Luanda");
    ids.add("Africa/Lubumbashi");
    ids.add("Africa/Lusaka");
    ids.add("Africa/Malabo");
    ids.add("Africa/Maputo");
    ids.add("Africa/Maseru");
    ids.add("Africa/Mbabane");
    ids.add("Africa/Mogadishu");
    ids.add("Africa/Monrovia");
    ids.add("Africa/Nairobi");
    ids.add("Africa/Ndjamena");
    ids.add("Africa/Niamey");
    ids.add("Africa/Nouakchott");
    ids.add("Africa/Ouagadougou");
    ids.add("Africa/Porto-Novo");
    ids.add("Africa/Sao_Tome");
    ids.add("Africa/Timbuktu");
    ids.add("Africa/Tripoli");
    ids.add("Africa/Tunis");
    ids.add("Africa/Windhoek");
    ids.add("America/Adak");
    ids.add("America/Anchorage");
    ids.add("America/Anguilla");
    ids.add("America/Antigua");
    ids.add("America/Araguaina");
    ids.add("America/Argentina/Buenos_Aires");
    ids.add("America/Argentina/Catamarca");
    ids.add("America/Argentina/ComodRivadavia");
    ids.add("America/Argentina/Cordoba");
    ids.add("America/Argentina/Jujuy");
    ids.add("America/Argentina/La_Rioja");
    ids.add("America/Argentina/Mendoza");
    ids.add("America/Argentina/Rio_Gallegos");
    ids.add("America/Argentina/Salta");
    ids.add("America/Argentina/San_Juan");
    ids.add("America/Argentina/San_Luis");
    ids.add("America/Argentina/Tucuman");
    ids.add("America/Argentina/Ushuaia");
    ids.add("America/Aruba");
    ids.add("America/Asuncion");
    ids.add("America/Atikokan");
    ids.add("America/Atka");
    ids.add("America/Bahia");
    ids.add("America/Bahia_Banderas");
    ids.add("America/Barbados");
    ids.add("America/Belem");
    ids.add("America/Belize");
    ids.add("America/Blanc-Sablon");
    ids.add("America/Boa_Vista");
    ids.add("America/Bogota");
    ids.add("America/Boise");
    ids.add("America/Buenos_Aires");
    ids.add("America/Cambridge_Bay");
    ids.add("America/Campo_Grande");
    ids.add("America/Cancun");
    ids.add("America/Caracas");
    ids.add("America/Catamarca");
    ids.add("America/Cayenne");
    ids.add("America/Cayman");
    ids.add("America/Chicago");
    ids.add("America/Chihuahua");
    ids.add("America/Coral_Harbour");
    ids.add("America/Cordoba");
    ids.add("America/Costa_Rica");
    ids.add("America/Creston");
    ids.add("America/Cuiaba");
    ids.add("America/Curacao");
    ids.add("America/Danmarkshavn");
    ids.add("America/Dawson");
    ids.add("America/Dawson_Creek");
    ids.add("America/Denver");
    ids.add("America/Detroit");
    ids.add("America/Dominica");
    ids.add("America/Edmonton");
    ids.add("America/Eirunepe");
    ids.add("America/El_Salvador");
    ids.add("America/Ensenada");
    ids.add("America/Fort_Nelson");
    ids.add("America/Fort_Wayne");
    ids.add("America/Fortaleza");
    ids.add("America/Glace_Bay");
    ids.add("America/Godthab");
    ids.add("America/Goose_Bay");
    ids.add("America/Grand_Turk");
    ids.add("America/Grenada");
    ids.add("America/Guadeloupe");
    ids.add("America/Guatemala");
    ids.add("America/Guayaquil");
    ids.add("America/Guyana");
    ids.add("America/Halifax");
    ids.add("America/Havana");
    ids.add("America/Hermosillo");
    ids.add("America/Indiana/Indianapolis");
    ids.add("America/Indiana/Knox");
    ids.add("America/Indiana/Marengo");
    ids.add("America/Indiana/Petersburg");
    ids.add("America/Indiana/Tell_City");
    ids.add("America/Indiana/Vevay");
    ids.add("America/Indiana/Vincennes");
    ids.add("America/Indiana/Winamac");
    ids.add("America/Indianapolis");
    ids.add("America/Inuvik");
    ids.add("America/Iqaluit");
    ids.add("America/Jamaica");
    ids.add("America/Jujuy");
    ids.add("America/Juneau");
    ids.add("America/Kentucky/Louisville");
    ids.add("America/Kentucky/Monticello");
    ids.add("America/Knox_IN");
    ids.add("America/Kralendijk");
    ids.add("America/La_Paz");
    ids.add("America/Lima");
    ids.add("America/Los_Angeles");
    ids.add("America/Louisville");
    ids.add("America/Lower_Princes");
    ids.add("America/Maceio");
    ids.add("America/Managua");
    ids.add("America/Manaus");
    ids.add("America/Marigot");
    ids.add("America/Martinique");
    ids.add("America/Matamoros");
    ids.add("America/Mazatlan");
    ids.add("America/Mendoza");
    ids.add("America/Menominee");
    ids.add("America/Merida");
    ids.add("America/Metlakatla");
    ids.add("America/Mexico_City");
    ids.add("America/Miquelon");
    ids.add("America/Moncton");
    ids.add("America/Monterrey");
    ids.add("America/Montevideo");
    ids.add("America/Montreal");
    ids.add("America/Montserrat");
    ids.add("America/Nassau");
    ids.add("America/New_York");
    ids.add("America/Nipigon");
    ids.add("America/Nome");
    ids.add("America/Noronha");
    ids.add("America/North_Dakota/Beulah");
    ids.add("America/North_Dakota/Center");
    ids.add("America/North_Dakota/New_Salem");
    ids.add("America/Ojinaga");
    ids.add("America/Panama");
    ids.add("America/Pangnirtung");
    ids.add("America/Paramaribo");
    ids.add("America/Phoenix");
    ids.add("America/Port-au-Prince");
    ids.add("America/Port_of_Spain");
    ids.add("America/Porto_Acre");
    ids.add("America/Porto_Velho");
    ids.add("America/Puerto_Rico");
    ids.add("America/Punta_Arenas");
    ids.add("America/Rainy_River");
    ids.add("America/Rankin_Inlet");
    ids.add("America/Recife");
    ids.add("America/Regina");
    ids.add("America/Resolute");
    ids.add("America/Rio_Branco");
    ids.add("America/Rosario");
    ids.add("America/Santa_Isabel");
    ids.add("America/Santarem");
    ids.add("America/Santiago");
    ids.add("America/Santo_Domingo");
    ids.add("America/Sao_Paulo");
    ids.add("America/Scoresbysund");
    ids.add("America/Shiprock");
    ids.add("America/Sitka");
    ids.add("America/St_Barthelemy");
    ids.add("America/St_Johns");
    ids.add("America/St_Kitts");
    ids.add("America/St_Lucia");
    ids.add("America/St_Thomas");
    ids.add("America/St_Vincent");
    ids.add("America/Swift_Current");
    ids.add("America/Tegucigalpa");
    ids.add("America/Thule");
    ids.add("America/Thunder_Bay");
    ids.add("America/Tijuana");
    ids.add("America/Toronto");
    ids.add("America/Tortola");
    ids.add("America/Vancouver");
    ids.add("America/Virgin");
    ids.add("America/Whitehorse");
    ids.add("America/Winnipeg");
    ids.add("America/Yakutat");
    ids.add("America/Yellowknife");
    ids.add("Antarctica/Casey");
    ids.add("Antarctica/Davis");
    ids.add("Antarctica/DumontDUrville");
    ids.add("Antarctica/Macquarie");
    ids.add("Antarctica/Mawson");
    ids.add("Antarctica/McMurdo");
    ids.add("Antarctica/Palmer");
    ids.add("Antarctica/Rothera");
    ids.add("Antarctica/South_Pole");
    ids.add("Antarctica/Syowa");
    ids.add("Antarctica/Troll");
    ids.add("Antarctica/Vostok");
    ids.add("Arctic/Longyearbyen");
    ids.add("Asia/Aden");
    ids.add("Asia/Almaty");
    ids.add("Asia/Amman");
    ids.add("Asia/Anadyr");
    ids.add("Asia/Aqtau");
    ids.add("Asia/Aqtobe");
    ids.add("Asia/Ashgabat");
    ids.add("Asia/Ashkhabad");
    ids.add("Asia/Atyrau");
    ids.add("Asia/Baghdad");
    ids.add("Asia/Bahrain");
    ids.add("Asia/Baku");
    ids.add("Asia/Bangkok");
    ids.add("Asia/Barnaul");
    ids.add("Asia/Beirut");
    ids.add("Asia/Bishkek");
    ids.add("Asia/Brunei");
    ids.add("Asia/Calcutta");
    ids.add("Asia/Chita");
    ids.add("Asia/Choibalsan");
    ids.add("Asia/Chongqing");
    ids.add("Asia/Chungking");
    ids.add("Asia/Colombo");
    ids.add("Asia/Dacca");
    ids.add("Asia/Damascus");
    ids.add("Asia/Dhaka");
    ids.add("Asia/Dili");
    ids.add("Asia/Dubai");
    ids.add("Asia/Dushanbe");
    ids.add("Asia/Famagusta");
    ids.add("Asia/Gaza");
    ids.add("Asia/Harbin");
    ids.add("Asia/Hebron");
    ids.add("Asia/Ho_Chi_Minh");
    ids.add("Asia/Hong_Kong");
    ids.add("Asia/Hovd");
    ids.add("Asia/Irkutsk");
    ids.add("Asia/Istanbul");
    ids.add("Asia/Jakarta");
    ids.add("Asia/Jayapura");
    ids.add("Asia/Jerusalem");
    ids.add("Asia/Kabul");
    ids.add("Asia/Kamchatka");
    ids.add("Asia/Karachi");
    ids.add("Asia/Kashgar");
    ids.add("Asia/Kathmandu");
    ids.add("Asia/Katmandu");
    ids.add("Asia/Khandyga");
    ids.add("Asia/Kolkata");
    ids.add("Asia/Krasnoyarsk");
    ids.add("Asia/Kuala_Lumpur");
    ids.add("Asia/Kuching");
    ids.add("Asia/Kuwait");
    ids.add("Asia/Macao");
    ids.add("Asia/Macau");
    ids.add("Asia/Magadan");
    ids.add("Asia/Makassar");
    ids.add("Asia/Manila");
    ids.add("Asia/Muscat");
    ids.add("Asia/Nicosia");
    ids.add("Asia/Novokuznetsk");
    ids.add("Asia/Novosibirsk");
    ids.add("Asia/Omsk");
    ids.add("Asia/Oral");
    ids.add("Asia/Phnom_Penh");
    ids.add("Asia/Pontianak");
    ids.add("Asia/Pyongyang");
    ids.add("Asia/Qatar");
    ids.add("Asia/Qyzylorda");
    ids.add("Asia/Rangoon");
    ids.add("Asia/Riyadh");
    ids.add("Asia/Saigon");
    ids.add("Asia/Sakhalin");
    ids.add("Asia/Samarkand");
    ids.add("Asia/Seoul");
    ids.add("Asia/Shanghai");
    ids.add("Asia/Singapore");
    ids.add("Asia/Srednekolymsk");
    ids.add("Asia/Taipei");
    ids.add("Asia/Tashkent");
    ids.add("Asia/Tbilisi");
    ids.add("Asia/Tehran");
    ids.add("Asia/Tel_Aviv");
    ids.add("Asia/Thimbu");
    ids.add("Asia/Thimphu");
    ids.add("Asia/Tokyo");
    ids.add("Asia/Tomsk");
    ids.add("Asia/Ujung_Pandang");
    ids.add("Asia/Ulaanbaatar");
    ids.add("Asia/Ulan_Bator");
    ids.add("Asia/Urumqi");
    ids.add("Asia/Ust-Nera");
    ids.add("Asia/Vientiane");
    ids.add("Asia/Vladivostok");
    ids.add("Asia/Yakutsk");
    ids.add("Asia/Yangon");
    ids.add("Asia/Yekaterinburg");
    ids.add("Asia/Yerevan");
    ids.add("Atlantic/Azores");
    ids.add("Atlantic/Bermuda");
    ids.add("Atlantic/Canary");
    ids.add("Atlantic/Cape_Verde");
    ids.add("Atlantic/Faeroe");
    ids.add("Atlantic/Faroe");
    ids.add("Atlantic/Jan_Mayen");
    ids.add("Atlantic/Madeira");
    ids.add("Atlantic/Reykjavik");
    ids.add("Atlantic/South_Georgia");
    ids.add("Atlantic/St_Helena");
    ids.add("Atlantic/Stanley");
    ids.add("Australia/ACT");
    ids.add("Australia/Adelaide");
    ids.add("Australia/Brisbane");
    ids.add("Australia/Broken_Hill");
    ids.add("Australia/Canberra");
    ids.add("Australia/Currie");
    ids.add("Australia/Darwin");
    ids.add("Australia/Eucla");
    ids.add("Australia/Hobart");
    ids.add("Australia/LHI");
    ids.add("Australia/Lindeman");
    ids.add("Australia/Lord_Howe");
    ids.add("Australia/Melbourne");
    ids.add("Australia/NSW");
    ids.add("Australia/North");
    ids.add("Australia/Perth");
    ids.add("Australia/Queensland");
    ids.add("Australia/South");
    ids.add("Australia/Sydney");
    ids.add("Australia/Tasmania");
    ids.add("Australia/Victoria");
    ids.add("Australia/West");
    ids.add("Australia/Yancowinna");
    ids.add("Brazil/Acre");
    ids.add("Brazil/DeNoronha");
    ids.add("Brazil/East");
    ids.add("Brazil/West");
    ids.add("CET");
    ids.add("CST6CDT");
    ids.add("Canada/Atlantic");
    ids.add("Canada/Central");
    ids.add("Canada/East-Saskatchewan");
    ids.add("Canada/Eastern");
    ids.add("Canada/Mountain");
    ids.add("Canada/Newfoundland");
    ids.add("Canada/Pacific");
    ids.add("Canada/Saskatchewan");
    ids.add("Canada/Yukon");
    ids.add("Chile/Continental");
    ids.add("Chile/EasterIsland");
    ids.add("Cuba");
    ids.add("EET");
    ids.add("EST");
    ids.add("EST5EDT");
    ids.add("Egypt");
    ids.add("Eire");
    ids.add("Etc/GMT");
    ids.add("Etc/GMT+0");
    ids.add("Etc/GMT+1");
    ids.add("Etc/GMT+10");
    ids.add("Etc/GMT+11");
    ids.add("Etc/GMT+12");
    ids.add("Etc/GMT+2");
    ids.add("Etc/GMT+3");
    ids.add("Etc/GMT+4");
    ids.add("Etc/GMT+5");
    ids.add("Etc/GMT+6");
    ids.add("Etc/GMT+7");
    ids.add("Etc/GMT+8");
    ids.add("Etc/GMT+9");
    ids.add("Etc/GMT-0");
    ids.add("Etc/GMT-1");
    ids.add("Etc/GMT-10");
    ids.add("Etc/GMT-11");
    ids.add("Etc/GMT-12");
    ids.add("Etc/GMT-13");
    ids.add("Etc/GMT-14");
    ids.add("Etc/GMT-2");
    ids.add("Etc/GMT-3");
    ids.add("Etc/GMT-4");
    ids.add("Etc/GMT-5");
    ids.add("Etc/GMT-6");
    ids.add("Etc/GMT-7");
    ids.add("Etc/GMT-8");
    ids.add("Etc/GMT-9");
    ids.add("Etc/GMT0");
    ids.add("Etc/Greenwich");
    ids.add("Etc/UCT");
    ids.add("Etc/UTC");
    ids.add("Etc/Universal");
    ids.add("Etc/Zulu");
    ids.add("Europe/Amsterdam");
    ids.add("Europe/Andorra");
    ids.add("Europe/Astrakhan");
    ids.add("Europe/Athens");
    ids.add("Europe/Belfast");
    ids.add("Europe/Belgrade");
    ids.add("Europe/Berlin");
    ids.add("Europe/Bratislava");
    ids.add("Europe/Brussels");
    ids.add("Europe/Bucharest");
    ids.add("Europe/Budapest");
    ids.add("Europe/Busingen");
    ids.add("Europe/Chisinau");
    ids.add("Europe/Copenhagen");
    ids.add("Europe/Dublin");
    ids.add("Europe/Gibraltar");
    ids.add("Europe/Guernsey");
    ids.add("Europe/Helsinki");
    ids.add("Europe/Isle_of_Man");
    ids.add("Europe/Istanbul");
    ids.add("Europe/Jersey");
    ids.add("Europe/Kaliningrad");
    ids.add("Europe/Kiev");
    ids.add("Europe/Kirov");
    ids.add("Europe/Lisbon");
    ids.add("Europe/Ljubljana");
    ids.add("Europe/London");
    ids.add("Europe/Luxembourg");
    ids.add("Europe/Madrid");
    ids.add("Europe/Malta");
    ids.add("Europe/Mariehamn");
    ids.add("Europe/Minsk");
    ids.add("Europe/Monaco");
    ids.add("Europe/Moscow");
    ids.add("Europe/Nicosia");
    ids.add("Europe/Oslo");
    ids.add("Europe/Paris");
    ids.add("Europe/Podgorica");
    ids.add("Europe/Prague");
    ids.add("Europe/Riga");
    ids.add("Europe/Rome");
    ids.add("Europe/Samara");
    ids.add("Europe/San_Marino");
    ids.add("Europe/Sarajevo");
    ids.add("Europe/Saratov");
    ids.add("Europe/Simferopol");
    ids.add("Europe/Skopje");
    ids.add("Europe/Sofia");
    ids.add("Europe/Stockholm");
    ids.add("Europe/Tallinn");
    ids.add("Europe/Tirane");
    ids.add("Europe/Tiraspol");
    ids.add("Europe/Ulyanovsk");
    ids.add("Europe/Uzhgorod");
    ids.add("Europe/Vaduz");
    ids.add("Europe/Vatican");
    ids.add("Europe/Vienna");
    ids.add("Europe/Vilnius");
    ids.add("Europe/Volgograd");
    ids.add("Europe/Warsaw");
    ids.add("Europe/Zagreb");
    ids.add("Europe/Zaporozhye");
    ids.add("Europe/Zurich");
    ids.add("GB");
    ids.add("GB-Eire");
    ids.add("Greenwich");
    ids.add("HST");
    ids.add("Hongkong");
    ids.add("Iceland");
    ids.add("Indian/Antananarivo");
    ids.add("Indian/Chagos");
    ids.add("Indian/Christmas");
    ids.add("Indian/Cocos");
    ids.add("Indian/Comoro");
    ids.add("Indian/Kerguelen");
    ids.add("Indian/Mahe");
    ids.add("Indian/Maldives");
    ids.add("Indian/Mauritius");
    ids.add("Indian/Mayotte");
    ids.add("Indian/Reunion");
    ids.add("Iran");
    ids.add("Israel");
    ids.add("Jamaica");
    ids.add("Japan");
    ids.add("Kwajalein");
    ids.add("Libya");
    ids.add("MET");
    ids.add("MST");
    ids.add("MST7MDT");
    ids.add("Mexico/BajaNorte");
    ids.add("Mexico/BajaSur");
    ids.add("Mexico/General");
    ids.add("NZ");
    ids.add("NZ-CHAT");
    ids.add("Navajo");
    ids.add("PRC");
    ids.add("PST8PDT");
    ids.add("Pacific/Apia");
    ids.add("Pacific/Auckland");
    ids.add("Pacific/Bougainville");
    ids.add("Pacific/Chatham");
    ids.add("Pacific/Chuuk");
    ids.add("Pacific/Easter");
    ids.add("Pacific/Efate");
    ids.add("Pacific/Enderbury");
    ids.add("Pacific/Fakaofo");
    ids.add("Pacific/Fiji");
    ids.add("Pacific/Funafuti");
    ids.add("Pacific/Galapagos");
    ids.add("Pacific/Gambier");
    ids.add("Pacific/Guadalcanal");
    ids.add("Pacific/Guam");
    ids.add("Pacific/Honolulu");
    ids.add("Pacific/Johnston");
    ids.add("Pacific/Kiritimati");
    ids.add("Pacific/Kosrae");
    ids.add("Pacific/Kwajalein");
    ids.add("Pacific/Majuro");
    ids.add("Pacific/Marquesas");
    ids.add("Pacific/Midway");
    ids.add("Pacific/Nauru");
    ids.add("Pacific/Niue");
    ids.add("Pacific/Norfolk");
    ids.add("Pacific/Noumea");
    ids.add("Pacific/Pago_Pago");
    ids.add("Pacific/Palau");
    ids.add("Pacific/Pitcairn");
    ids.add("Pacific/Pohnpei");
    ids.add("Pacific/Ponape");
    ids.add("Pacific/Port_Moresby");
    ids.add("Pacific/Rarotonga");
    ids.add("Pacific/Saipan");
    ids.add("Pacific/Samoa");
    ids.add("Pacific/Tahiti");
    ids.add("Pacific/Tarawa");
    ids.add("Pacific/Tongatapu");
    ids.add("Pacific/Truk");
    ids.add("Pacific/Wake");
    ids.add("Pacific/Wallis");
    ids.add("Pacific/Yap");
    ids.add("Poland");
    ids.add("Portugal");
    ids.add("ROC");
    ids.add("ROK");
    ids.add("Singapore");
    ids.add("Turkey");
    ids.add("UCT");
    ids.add("US/Alaska");
    ids.add("US/Aleutian");
    ids.add("US/Arizona");
    ids.add("US/Central");
    ids.add("US/East-Indiana");
    ids.add("US/Eastern");
    ids.add("US/Hawaii");
    ids.add("US/Indiana-Starke");
    ids.add("US/Michigan");
    ids.add("US/Mountain");
    ids.add("US/Pacific");
    ids.add("US/Samoa");
    ids.add("Universal");
    ids.add("W-SU");
    ids.add("WET");
    ids.add("Zulu");
    REGION_IDS = Collections.unmodifiableSet(ids);
  }

  static String provideFileName(String zoneId) {
    switch (zoneId) {
      case "Africa/Abidjan": return "tzdb/africa-abidjan.dat";
      case "Africa/Accra": return "tzdb/africa-accra.dat";
      case "Africa/Addis_Ababa": return "tzdb/africa-addis_ababa.dat";
      case "Africa/Algiers": return "tzdb/africa-algiers.dat";
      case "Africa/Asmara": return "tzdb/africa-asmara.dat";
      case "Africa/Asmera": return "tzdb/africa-asmera.dat";
      case "Africa/Bamako": return "tzdb/africa-bamako.dat";
      case "Africa/Bangui": return "tzdb/africa-bangui.dat";
      case "Africa/Banjul": return "tzdb/africa-banjul.dat";
      case "Africa/Bissau": return "tzdb/africa-bissau.dat";
      case "Africa/Blantyre": return "tzdb/africa-blantyre.dat";
      case "Africa/Brazzaville": return "tzdb/africa-brazzaville.dat";
      case "Africa/Bujumbura": return "tzdb/africa-bujumbura.dat";
      case "Africa/Cairo": return "tzdb/africa-cairo.dat";
      case "Africa/Casablanca": return "tzdb/africa-casablanca.dat";
      case "Africa/Ceuta": return "tzdb/africa-ceuta.dat";
      case "Africa/Conakry": return "tzdb/africa-conakry.dat";
      case "Africa/Dakar": return "tzdb/africa-dakar.dat";
      case "Africa/Dar_es_Salaam": return "tzdb/africa-dar_es_salaam.dat";
      case "Africa/Djibouti": return "tzdb/africa-djibouti.dat";
      case "Africa/Douala": return "tzdb/africa-douala.dat";
      case "Africa/El_Aaiun": return "tzdb/africa-el_aaiun.dat";
      case "Africa/Freetown": return "tzdb/africa-freetown.dat";
      case "Africa/Gaborone": return "tzdb/africa-gaborone.dat";
      case "Africa/Harare": return "tzdb/africa-harare.dat";
      case "Africa/Johannesburg": return "tzdb/africa-johannesburg.dat";
      case "Africa/Juba": return "tzdb/africa-juba.dat";
      case "Africa/Kampala": return "tzdb/africa-kampala.dat";
      case "Africa/Khartoum": return "tzdb/africa-khartoum.dat";
      case "Africa/Kigali": return "tzdb/africa-kigali.dat";
      case "Africa/Kinshasa": return "tzdb/africa-kinshasa.dat";
      case "Africa/Lagos": return "tzdb/africa-lagos.dat";
      case "Africa/Libreville": return "tzdb/africa-libreville.dat";
      case "Africa/Lome": return "tzdb/africa-lome.dat";
      case "Africa/Luanda": return "tzdb/africa-luanda.dat";
      case "Africa/Lubumbashi": return "tzdb/africa-lubumbashi.dat";
      case "Africa/Lusaka": return "tzdb/africa-lusaka.dat";
      case "Africa/Malabo": return "tzdb/africa-malabo.dat";
      case "Africa/Maputo": return "tzdb/africa-maputo.dat";
      case "Africa/Maseru": return "tzdb/africa-maseru.dat";
      case "Africa/Mbabane": return "tzdb/africa-mbabane.dat";
      case "Africa/Mogadishu": return "tzdb/africa-mogadishu.dat";
      case "Africa/Monrovia": return "tzdb/africa-monrovia.dat";
      case "Africa/Nairobi": return "tzdb/africa-nairobi.dat";
      case "Africa/Ndjamena": return "tzdb/africa-ndjamena.dat";
      case "Africa/Niamey": return "tzdb/africa-niamey.dat";
      case "Africa/Nouakchott": return "tzdb/africa-nouakchott.dat";
      case "Africa/Ouagadougou": return "tzdb/africa-ouagadougou.dat";
      case "Africa/Porto-Novo": return "tzdb/africa-porto-novo.dat";
      case "Africa/Sao_Tome": return "tzdb/africa-sao_tome.dat";
      case "Africa/Timbuktu": return "tzdb/africa-timbuktu.dat";
      case "Africa/Tripoli": return "tzdb/africa-tripoli.dat";
      case "Africa/Tunis": return "tzdb/africa-tunis.dat";
      case "Africa/Windhoek": return "tzdb/africa-windhoek.dat";
      case "America/Adak": return "tzdb/america-adak.dat";
      case "America/Anchorage": return "tzdb/america-anchorage.dat";
      case "America/Anguilla": return "tzdb/america-anguilla.dat";
      case "America/Antigua": return "tzdb/america-antigua.dat";
      case "America/Araguaina": return "tzdb/america-araguaina.dat";
      case "America/Argentina/Buenos_Aires": return "tzdb/america-argentina-buenos_aires.dat";
      case "America/Argentina/Catamarca": return "tzdb/america-argentina-catamarca.dat";
      case "America/Argentina/ComodRivadavia": return "tzdb/america-argentina-comodrivadavia.dat";
      case "America/Argentina/Cordoba": return "tzdb/america-argentina-cordoba.dat";
      case "America/Argentina/Jujuy": return "tzdb/america-argentina-jujuy.dat";
      case "America/Argentina/La_Rioja": return "tzdb/america-argentina-la_rioja.dat";
      case "America/Argentina/Mendoza": return "tzdb/america-argentina-mendoza.dat";
      case "America/Argentina/Rio_Gallegos": return "tzdb/america-argentina-rio_gallegos.dat";
      case "America/Argentina/Salta": return "tzdb/america-argentina-salta.dat";
      case "America/Argentina/San_Juan": return "tzdb/america-argentina-san_juan.dat";
      case "America/Argentina/San_Luis": return "tzdb/america-argentina-san_luis.dat";
      case "America/Argentina/Tucuman": return "tzdb/america-argentina-tucuman.dat";
      case "America/Argentina/Ushuaia": return "tzdb/america-argentina-ushuaia.dat";
      case "America/Aruba": return "tzdb/america-aruba.dat";
      case "America/Asuncion": return "tzdb/america-asuncion.dat";
      case "America/Atikokan": return "tzdb/america-atikokan.dat";
      case "America/Atka": return "tzdb/america-atka.dat";
      case "America/Bahia": return "tzdb/america-bahia.dat";
      case "America/Bahia_Banderas": return "tzdb/america-bahia_banderas.dat";
      case "America/Barbados": return "tzdb/america-barbados.dat";
      case "America/Belem": return "tzdb/america-belem.dat";
      case "America/Belize": return "tzdb/america-belize.dat";
      case "America/Blanc-Sablon": return "tzdb/america-blanc-sablon.dat";
      case "America/Boa_Vista": return "tzdb/america-boa_vista.dat";
      case "America/Bogota": return "tzdb/america-bogota.dat";
      case "America/Boise": return "tzdb/america-boise.dat";
      case "America/Buenos_Aires": return "tzdb/america-buenos_aires.dat";
      case "America/Cambridge_Bay": return "tzdb/america-cambridge_bay.dat";
      case "America/Campo_Grande": return "tzdb/america-campo_grande.dat";
      case "America/Cancun": return "tzdb/america-cancun.dat";
      case "America/Caracas": return "tzdb/america-caracas.dat";
      case "America/Catamarca": return "tzdb/america-catamarca.dat";
      case "America/Cayenne": return "tzdb/america-cayenne.dat";
      case "America/Cayman": return "tzdb/america-cayman.dat";
      case "America/Chicago": return "tzdb/america-chicago.dat";
      case "America/Chihuahua": return "tzdb/america-chihuahua.dat";
      case "America/Coral_Harbour": return "tzdb/america-coral_harbour.dat";
      case "America/Cordoba": return "tzdb/america-cordoba.dat";
      case "America/Costa_Rica": return "tzdb/america-costa_rica.dat";
      case "America/Creston": return "tzdb/america-creston.dat";
      case "America/Cuiaba": return "tzdb/america-cuiaba.dat";
      case "America/Curacao": return "tzdb/america-curacao.dat";
      case "America/Danmarkshavn": return "tzdb/america-danmarkshavn.dat";
      case "America/Dawson": return "tzdb/america-dawson.dat";
      case "America/Dawson_Creek": return "tzdb/america-dawson_creek.dat";
      case "America/Denver": return "tzdb/america-denver.dat";
      case "America/Detroit": return "tzdb/america-detroit.dat";
      case "America/Dominica": return "tzdb/america-dominica.dat";
      case "America/Edmonton": return "tzdb/america-edmonton.dat";
      case "America/Eirunepe": return "tzdb/america-eirunepe.dat";
      case "America/El_Salvador": return "tzdb/america-el_salvador.dat";
      case "America/Ensenada": return "tzdb/america-ensenada.dat";
      case "America/Fort_Nelson": return "tzdb/america-fort_nelson.dat";
      case "America/Fort_Wayne": return "tzdb/america-fort_wayne.dat";
      case "America/Fortaleza": return "tzdb/america-fortaleza.dat";
      case "America/Glace_Bay": return "tzdb/america-glace_bay.dat";
      case "America/Godthab": return "tzdb/america-godthab.dat";
      case "America/Goose_Bay": return "tzdb/america-goose_bay.dat";
      case "America/Grand_Turk": return "tzdb/america-grand_turk.dat";
      case "America/Grenada": return "tzdb/america-grenada.dat";
      case "America/Guadeloupe": return "tzdb/america-guadeloupe.dat";
      case "America/Guatemala": return "tzdb/america-guatemala.dat";
      case "America/Guayaquil": return "tzdb/america-guayaquil.dat";
      case "America/Guyana": return "tzdb/america-guyana.dat";
      case "America/Halifax": return "tzdb/america-halifax.dat";
      case "America/Havana": return "tzdb/america-havana.dat";
      case "America/Hermosillo": return "tzdb/america-hermosillo.dat";
      case "America/Indiana/Indianapolis": return "tzdb/america-indiana-indianapolis.dat";
      case "America/Indiana/Knox": return "tzdb/america-indiana-knox.dat";
      case "America/Indiana/Marengo": return "tzdb/america-indiana-marengo.dat";
      case "America/Indiana/Petersburg": return "tzdb/america-indiana-petersburg.dat";
      case "America/Indiana/Tell_City": return "tzdb/america-indiana-tell_city.dat";
      case "America/Indiana/Vevay": return "tzdb/america-indiana-vevay.dat";
      case "America/Indiana/Vincennes": return "tzdb/america-indiana-vincennes.dat";
      case "America/Indiana/Winamac": return "tzdb/america-indiana-winamac.dat";
      case "America/Indianapolis": return "tzdb/america-indianapolis.dat";
      case "America/Inuvik": return "tzdb/america-inuvik.dat";
      case "America/Iqaluit": return "tzdb/america-iqaluit.dat";
      case "America/Jamaica": return "tzdb/america-jamaica.dat";
      case "America/Jujuy": return "tzdb/america-jujuy.dat";
      case "America/Juneau": return "tzdb/america-juneau.dat";
      case "America/Kentucky/Louisville": return "tzdb/america-kentucky-louisville.dat";
      case "America/Kentucky/Monticello": return "tzdb/america-kentucky-monticello.dat";
      case "America/Knox_IN": return "tzdb/america-knox_in.dat";
      case "America/Kralendijk": return "tzdb/america-kralendijk.dat";
      case "America/La_Paz": return "tzdb/america-la_paz.dat";
      case "America/Lima": return "tzdb/america-lima.dat";
      case "America/Los_Angeles": return "tzdb/america-los_angeles.dat";
      case "America/Louisville": return "tzdb/america-louisville.dat";
      case "America/Lower_Princes": return "tzdb/america-lower_princes.dat";
      case "America/Maceio": return "tzdb/america-maceio.dat";
      case "America/Managua": return "tzdb/america-managua.dat";
      case "America/Manaus": return "tzdb/america-manaus.dat";
      case "America/Marigot": return "tzdb/america-marigot.dat";
      case "America/Martinique": return "tzdb/america-martinique.dat";
      case "America/Matamoros": return "tzdb/america-matamoros.dat";
      case "America/Mazatlan": return "tzdb/america-mazatlan.dat";
      case "America/Mendoza": return "tzdb/america-mendoza.dat";
      case "America/Menominee": return "tzdb/america-menominee.dat";
      case "America/Merida": return "tzdb/america-merida.dat";
      case "America/Metlakatla": return "tzdb/america-metlakatla.dat";
      case "America/Mexico_City": return "tzdb/america-mexico_city.dat";
      case "America/Miquelon": return "tzdb/america-miquelon.dat";
      case "America/Moncton": return "tzdb/america-moncton.dat";
      case "America/Monterrey": return "tzdb/america-monterrey.dat";
      case "America/Montevideo": return "tzdb/america-montevideo.dat";
      case "America/Montreal": return "tzdb/america-montreal.dat";
      case "America/Montserrat": return "tzdb/america-montserrat.dat";
      case "America/Nassau": return "tzdb/america-nassau.dat";
      case "America/New_York": return "tzdb/america-new_york.dat";
      case "America/Nipigon": return "tzdb/america-nipigon.dat";
      case "America/Nome": return "tzdb/america-nome.dat";
      case "America/Noronha": return "tzdb/america-noronha.dat";
      case "America/North_Dakota/Beulah": return "tzdb/america-north_dakota-beulah.dat";
      case "America/North_Dakota/Center": return "tzdb/america-north_dakota-center.dat";
      case "America/North_Dakota/New_Salem": return "tzdb/america-north_dakota-new_salem.dat";
      case "America/Ojinaga": return "tzdb/america-ojinaga.dat";
      case "America/Panama": return "tzdb/america-panama.dat";
      case "America/Pangnirtung": return "tzdb/america-pangnirtung.dat";
      case "America/Paramaribo": return "tzdb/america-paramaribo.dat";
      case "America/Phoenix": return "tzdb/america-phoenix.dat";
      case "America/Port-au-Prince": return "tzdb/america-port-au-prince.dat";
      case "America/Port_of_Spain": return "tzdb/america-port_of_spain.dat";
      case "America/Porto_Acre": return "tzdb/america-porto_acre.dat";
      case "America/Porto_Velho": return "tzdb/america-porto_velho.dat";
      case "America/Puerto_Rico": return "tzdb/america-puerto_rico.dat";
      case "America/Punta_Arenas": return "tzdb/america-punta_arenas.dat";
      case "America/Rainy_River": return "tzdb/america-rainy_river.dat";
      case "America/Rankin_Inlet": return "tzdb/america-rankin_inlet.dat";
      case "America/Recife": return "tzdb/america-recife.dat";
      case "America/Regina": return "tzdb/america-regina.dat";
      case "America/Resolute": return "tzdb/america-resolute.dat";
      case "America/Rio_Branco": return "tzdb/america-rio_branco.dat";
      case "America/Rosario": return "tzdb/america-rosario.dat";
      case "America/Santa_Isabel": return "tzdb/america-santa_isabel.dat";
      case "America/Santarem": return "tzdb/america-santarem.dat";
      case "America/Santiago": return "tzdb/america-santiago.dat";
      case "America/Santo_Domingo": return "tzdb/america-santo_domingo.dat";
      case "America/Sao_Paulo": return "tzdb/america-sao_paulo.dat";
      case "America/Scoresbysund": return "tzdb/america-scoresbysund.dat";
      case "America/Shiprock": return "tzdb/america-shiprock.dat";
      case "America/Sitka": return "tzdb/america-sitka.dat";
      case "America/St_Barthelemy": return "tzdb/america-st_barthelemy.dat";
      case "America/St_Johns": return "tzdb/america-st_johns.dat";
      case "America/St_Kitts": return "tzdb/america-st_kitts.dat";
      case "America/St_Lucia": return "tzdb/america-st_lucia.dat";
      case "America/St_Thomas": return "tzdb/america-st_thomas.dat";
      case "America/St_Vincent": return "tzdb/america-st_vincent.dat";
      case "America/Swift_Current": return "tzdb/america-swift_current.dat";
      case "America/Tegucigalpa": return "tzdb/america-tegucigalpa.dat";
      case "America/Thule": return "tzdb/america-thule.dat";
      case "America/Thunder_Bay": return "tzdb/america-thunder_bay.dat";
      case "America/Tijuana": return "tzdb/america-tijuana.dat";
      case "America/Toronto": return "tzdb/america-toronto.dat";
      case "America/Tortola": return "tzdb/america-tortola.dat";
      case "America/Vancouver": return "tzdb/america-vancouver.dat";
      case "America/Virgin": return "tzdb/america-virgin.dat";
      case "America/Whitehorse": return "tzdb/america-whitehorse.dat";
      case "America/Winnipeg": return "tzdb/america-winnipeg.dat";
      case "America/Yakutat": return "tzdb/america-yakutat.dat";
      case "America/Yellowknife": return "tzdb/america-yellowknife.dat";
      case "Antarctica/Casey": return "tzdb/antarctica-casey.dat";
      case "Antarctica/Davis": return "tzdb/antarctica-davis.dat";
      case "Antarctica/DumontDUrville": return "tzdb/antarctica-dumontdurville.dat";
      case "Antarctica/Macquarie": return "tzdb/antarctica-macquarie.dat";
      case "Antarctica/Mawson": return "tzdb/antarctica-mawson.dat";
      case "Antarctica/McMurdo": return "tzdb/antarctica-mcmurdo.dat";
      case "Antarctica/Palmer": return "tzdb/antarctica-palmer.dat";
      case "Antarctica/Rothera": return "tzdb/antarctica-rothera.dat";
      case "Antarctica/South_Pole": return "tzdb/antarctica-south_pole.dat";
      case "Antarctica/Syowa": return "tzdb/antarctica-syowa.dat";
      case "Antarctica/Troll": return "tzdb/antarctica-troll.dat";
      case "Antarctica/Vostok": return "tzdb/antarctica-vostok.dat";
      case "Arctic/Longyearbyen": return "tzdb/arctic-longyearbyen.dat";
      case "Asia/Aden": return "tzdb/asia-aden.dat";
      case "Asia/Almaty": return "tzdb/asia-almaty.dat";
      case "Asia/Amman": return "tzdb/asia-amman.dat";
      case "Asia/Anadyr": return "tzdb/asia-anadyr.dat";
      case "Asia/Aqtau": return "tzdb/asia-aqtau.dat";
      case "Asia/Aqtobe": return "tzdb/asia-aqtobe.dat";
      case "Asia/Ashgabat": return "tzdb/asia-ashgabat.dat";
      case "Asia/Ashkhabad": return "tzdb/asia-ashkhabad.dat";
      case "Asia/Atyrau": return "tzdb/asia-atyrau.dat";
      case "Asia/Baghdad": return "tzdb/asia-baghdad.dat";
      case "Asia/Bahrain": return "tzdb/asia-bahrain.dat";
      case "Asia/Baku": return "tzdb/asia-baku.dat";
      case "Asia/Bangkok": return "tzdb/asia-bangkok.dat";
      case "Asia/Barnaul": return "tzdb/asia-barnaul.dat";
      case "Asia/Beirut": return "tzdb/asia-beirut.dat";
      case "Asia/Bishkek": return "tzdb/asia-bishkek.dat";
      case "Asia/Brunei": return "tzdb/asia-brunei.dat";
      case "Asia/Calcutta": return "tzdb/asia-calcutta.dat";
      case "Asia/Chita": return "tzdb/asia-chita.dat";
      case "Asia/Choibalsan": return "tzdb/asia-choibalsan.dat";
      case "Asia/Chongqing": return "tzdb/asia-chongqing.dat";
      case "Asia/Chungking": return "tzdb/asia-chungking.dat";
      case "Asia/Colombo": return "tzdb/asia-colombo.dat";
      case "Asia/Dacca": return "tzdb/asia-dacca.dat";
      case "Asia/Damascus": return "tzdb/asia-damascus.dat";
      case "Asia/Dhaka": return "tzdb/asia-dhaka.dat";
      case "Asia/Dili": return "tzdb/asia-dili.dat";
      case "Asia/Dubai": return "tzdb/asia-dubai.dat";
      case "Asia/Dushanbe": return "tzdb/asia-dushanbe.dat";
      case "Asia/Famagusta": return "tzdb/asia-famagusta.dat";
      case "Asia/Gaza": return "tzdb/asia-gaza.dat";
      case "Asia/Harbin": return "tzdb/asia-harbin.dat";
      case "Asia/Hebron": return "tzdb/asia-hebron.dat";
      case "Asia/Ho_Chi_Minh": return "tzdb/asia-ho_chi_minh.dat";
      case "Asia/Hong_Kong": return "tzdb/asia-hong_kong.dat";
      case "Asia/Hovd": return "tzdb/asia-hovd.dat";
      case "Asia/Irkutsk": return "tzdb/asia-irkutsk.dat";
      case "Asia/Istanbul": return "tzdb/asia-istanbul.dat";
      case "Asia/Jakarta": return "tzdb/asia-jakarta.dat";
      case "Asia/Jayapura": return "tzdb/asia-jayapura.dat";
      case "Asia/Jerusalem": return "tzdb/asia-jerusalem.dat";
      case "Asia/Kabul": return "tzdb/asia-kabul.dat";
      case "Asia/Kamchatka": return "tzdb/asia-kamchatka.dat";
      case "Asia/Karachi": return "tzdb/asia-karachi.dat";
      case "Asia/Kashgar": return "tzdb/asia-kashgar.dat";
      case "Asia/Kathmandu": return "tzdb/asia-kathmandu.dat";
      case "Asia/Katmandu": return "tzdb/asia-katmandu.dat";
      case "Asia/Khandyga": return "tzdb/asia-khandyga.dat";
      case "Asia/Kolkata": return "tzdb/asia-kolkata.dat";
      case "Asia/Krasnoyarsk": return "tzdb/asia-krasnoyarsk.dat";
      case "Asia/Kuala_Lumpur": return "tzdb/asia-kuala_lumpur.dat";
      case "Asia/Kuching": return "tzdb/asia-kuching.dat";
      case "Asia/Kuwait": return "tzdb/asia-kuwait.dat";
      case "Asia/Macao": return "tzdb/asia-macao.dat";
      case "Asia/Macau": return "tzdb/asia-macau.dat";
      case "Asia/Magadan": return "tzdb/asia-magadan.dat";
      case "Asia/Makassar": return "tzdb/asia-makassar.dat";
      case "Asia/Manila": return "tzdb/asia-manila.dat";
      case "Asia/Muscat": return "tzdb/asia-muscat.dat";
      case "Asia/Nicosia": return "tzdb/asia-nicosia.dat";
      case "Asia/Novokuznetsk": return "tzdb/asia-novokuznetsk.dat";
      case "Asia/Novosibirsk": return "tzdb/asia-novosibirsk.dat";
      case "Asia/Omsk": return "tzdb/asia-omsk.dat";
      case "Asia/Oral": return "tzdb/asia-oral.dat";
      case "Asia/Phnom_Penh": return "tzdb/asia-phnom_penh.dat";
      case "Asia/Pontianak": return "tzdb/asia-pontianak.dat";
      case "Asia/Pyongyang": return "tzdb/asia-pyongyang.dat";
      case "Asia/Qatar": return "tzdb/asia-qatar.dat";
      case "Asia/Qyzylorda": return "tzdb/asia-qyzylorda.dat";
      case "Asia/Rangoon": return "tzdb/asia-rangoon.dat";
      case "Asia/Riyadh": return "tzdb/asia-riyadh.dat";
      case "Asia/Saigon": return "tzdb/asia-saigon.dat";
      case "Asia/Sakhalin": return "tzdb/asia-sakhalin.dat";
      case "Asia/Samarkand": return "tzdb/asia-samarkand.dat";
      case "Asia/Seoul": return "tzdb/asia-seoul.dat";
      case "Asia/Shanghai": return "tzdb/asia-shanghai.dat";
      case "Asia/Singapore": return "tzdb/asia-singapore.dat";
      case "Asia/Srednekolymsk": return "tzdb/asia-srednekolymsk.dat";
      case "Asia/Taipei": return "tzdb/asia-taipei.dat";
      case "Asia/Tashkent": return "tzdb/asia-tashkent.dat";
      case "Asia/Tbilisi": return "tzdb/asia-tbilisi.dat";
      case "Asia/Tehran": return "tzdb/asia-tehran.dat";
      case "Asia/Tel_Aviv": return "tzdb/asia-tel_aviv.dat";
      case "Asia/Thimbu": return "tzdb/asia-thimbu.dat";
      case "Asia/Thimphu": return "tzdb/asia-thimphu.dat";
      case "Asia/Tokyo": return "tzdb/asia-tokyo.dat";
      case "Asia/Tomsk": return "tzdb/asia-tomsk.dat";
      case "Asia/Ujung_Pandang": return "tzdb/asia-ujung_pandang.dat";
      case "Asia/Ulaanbaatar": return "tzdb/asia-ulaanbaatar.dat";
      case "Asia/Ulan_Bator": return "tzdb/asia-ulan_bator.dat";
      case "Asia/Urumqi": return "tzdb/asia-urumqi.dat";
      case "Asia/Ust-Nera": return "tzdb/asia-ust-nera.dat";
      case "Asia/Vientiane": return "tzdb/asia-vientiane.dat";
      case "Asia/Vladivostok": return "tzdb/asia-vladivostok.dat";
      case "Asia/Yakutsk": return "tzdb/asia-yakutsk.dat";
      case "Asia/Yangon": return "tzdb/asia-yangon.dat";
      case "Asia/Yekaterinburg": return "tzdb/asia-yekaterinburg.dat";
      case "Asia/Yerevan": return "tzdb/asia-yerevan.dat";
      case "Atlantic/Azores": return "tzdb/atlantic-azores.dat";
      case "Atlantic/Bermuda": return "tzdb/atlantic-bermuda.dat";
      case "Atlantic/Canary": return "tzdb/atlantic-canary.dat";
      case "Atlantic/Cape_Verde": return "tzdb/atlantic-cape_verde.dat";
      case "Atlantic/Faeroe": return "tzdb/atlantic-faeroe.dat";
      case "Atlantic/Faroe": return "tzdb/atlantic-faroe.dat";
      case "Atlantic/Jan_Mayen": return "tzdb/atlantic-jan_mayen.dat";
      case "Atlantic/Madeira": return "tzdb/atlantic-madeira.dat";
      case "Atlantic/Reykjavik": return "tzdb/atlantic-reykjavik.dat";
      case "Atlantic/South_Georgia": return "tzdb/atlantic-south_georgia.dat";
      case "Atlantic/St_Helena": return "tzdb/atlantic-st_helena.dat";
      case "Atlantic/Stanley": return "tzdb/atlantic-stanley.dat";
      case "Australia/ACT": return "tzdb/australia-act.dat";
      case "Australia/Adelaide": return "tzdb/australia-adelaide.dat";
      case "Australia/Brisbane": return "tzdb/australia-brisbane.dat";
      case "Australia/Broken_Hill": return "tzdb/australia-broken_hill.dat";
      case "Australia/Canberra": return "tzdb/australia-canberra.dat";
      case "Australia/Currie": return "tzdb/australia-currie.dat";
      case "Australia/Darwin": return "tzdb/australia-darwin.dat";
      case "Australia/Eucla": return "tzdb/australia-eucla.dat";
      case "Australia/Hobart": return "tzdb/australia-hobart.dat";
      case "Australia/LHI": return "tzdb/australia-lhi.dat";
      case "Australia/Lindeman": return "tzdb/australia-lindeman.dat";
      case "Australia/Lord_Howe": return "tzdb/australia-lord_howe.dat";
      case "Australia/Melbourne": return "tzdb/australia-melbourne.dat";
      case "Australia/NSW": return "tzdb/australia-nsw.dat";
      case "Australia/North": return "tzdb/australia-north.dat";
      case "Australia/Perth": return "tzdb/australia-perth.dat";
      case "Australia/Queensland": return "tzdb/australia-queensland.dat";
      case "Australia/South": return "tzdb/australia-south.dat";
      case "Australia/Sydney": return "tzdb/australia-sydney.dat";
      case "Australia/Tasmania": return "tzdb/australia-tasmania.dat";
      case "Australia/Victoria": return "tzdb/australia-victoria.dat";
      case "Australia/West": return "tzdb/australia-west.dat";
      case "Australia/Yancowinna": return "tzdb/australia-yancowinna.dat";
      case "Brazil/Acre": return "tzdb/brazil-acre.dat";
      case "Brazil/DeNoronha": return "tzdb/brazil-denoronha.dat";
      case "Brazil/East": return "tzdb/brazil-east.dat";
      case "Brazil/West": return "tzdb/brazil-west.dat";
      case "CET": return "tzdb/cet.dat";
      case "CST6CDT": return "tzdb/cst6cdt.dat";
      case "Canada/Atlantic": return "tzdb/canada-atlantic.dat";
      case "Canada/Central": return "tzdb/canada-central.dat";
      case "Canada/East-Saskatchewan": return "tzdb/canada-east-saskatchewan.dat";
      case "Canada/Eastern": return "tzdb/canada-eastern.dat";
      case "Canada/Mountain": return "tzdb/canada-mountain.dat";
      case "Canada/Newfoundland": return "tzdb/canada-newfoundland.dat";
      case "Canada/Pacific": return "tzdb/canada-pacific.dat";
      case "Canada/Saskatchewan": return "tzdb/canada-saskatchewan.dat";
      case "Canada/Yukon": return "tzdb/canada-yukon.dat";
      case "Chile/Continental": return "tzdb/chile-continental.dat";
      case "Chile/EasterIsland": return "tzdb/chile-easterisland.dat";
      case "Cuba": return "tzdb/cuba.dat";
      case "EET": return "tzdb/eet.dat";
      case "EST": return "tzdb/est.dat";
      case "EST5EDT": return "tzdb/est5edt.dat";
      case "Egypt": return "tzdb/egypt.dat";
      case "Eire": return "tzdb/eire.dat";
      case "Etc/GMT": return "tzdb/etc-gmt.dat";
      case "Etc/GMT+0": return "tzdb/etc-gmt+0.dat";
      case "Etc/GMT+1": return "tzdb/etc-gmt+1.dat";
      case "Etc/GMT+10": return "tzdb/etc-gmt+10.dat";
      case "Etc/GMT+11": return "tzdb/etc-gmt+11.dat";
      case "Etc/GMT+12": return "tzdb/etc-gmt+12.dat";
      case "Etc/GMT+2": return "tzdb/etc-gmt+2.dat";
      case "Etc/GMT+3": return "tzdb/etc-gmt+3.dat";
      case "Etc/GMT+4": return "tzdb/etc-gmt+4.dat";
      case "Etc/GMT+5": return "tzdb/etc-gmt+5.dat";
      case "Etc/GMT+6": return "tzdb/etc-gmt+6.dat";
      case "Etc/GMT+7": return "tzdb/etc-gmt+7.dat";
      case "Etc/GMT+8": return "tzdb/etc-gmt+8.dat";
      case "Etc/GMT+9": return "tzdb/etc-gmt+9.dat";
      case "Etc/GMT-0": return "tzdb/etc-gmt-0.dat";
      case "Etc/GMT-1": return "tzdb/etc-gmt-1.dat";
      case "Etc/GMT-10": return "tzdb/etc-gmt-10.dat";
      case "Etc/GMT-11": return "tzdb/etc-gmt-11.dat";
      case "Etc/GMT-12": return "tzdb/etc-gmt-12.dat";
      case "Etc/GMT-13": return "tzdb/etc-gmt-13.dat";
      case "Etc/GMT-14": return "tzdb/etc-gmt-14.dat";
      case "Etc/GMT-2": return "tzdb/etc-gmt-2.dat";
      case "Etc/GMT-3": return "tzdb/etc-gmt-3.dat";
      case "Etc/GMT-4": return "tzdb/etc-gmt-4.dat";
      case "Etc/GMT-5": return "tzdb/etc-gmt-5.dat";
      case "Etc/GMT-6": return "tzdb/etc-gmt-6.dat";
      case "Etc/GMT-7": return "tzdb/etc-gmt-7.dat";
      case "Etc/GMT-8": return "tzdb/etc-gmt-8.dat";
      case "Etc/GMT-9": return "tzdb/etc-gmt-9.dat";
      case "Etc/GMT0": return "tzdb/etc-gmt0.dat";
      case "Etc/Greenwich": return "tzdb/etc-greenwich.dat";
      case "Etc/UCT": return "tzdb/etc-uct.dat";
      case "Etc/UTC": return "tzdb/etc-utc.dat";
      case "Etc/Universal": return "tzdb/etc-universal.dat";
      case "Etc/Zulu": return "tzdb/etc-zulu.dat";
      case "Europe/Amsterdam": return "tzdb/europe-amsterdam.dat";
      case "Europe/Andorra": return "tzdb/europe-andorra.dat";
      case "Europe/Astrakhan": return "tzdb/europe-astrakhan.dat";
      case "Europe/Athens": return "tzdb/europe-athens.dat";
      case "Europe/Belfast": return "tzdb/europe-belfast.dat";
      case "Europe/Belgrade": return "tzdb/europe-belgrade.dat";
      case "Europe/Berlin": return "tzdb/europe-berlin.dat";
      case "Europe/Bratislava": return "tzdb/europe-bratislava.dat";
      case "Europe/Brussels": return "tzdb/europe-brussels.dat";
      case "Europe/Bucharest": return "tzdb/europe-bucharest.dat";
      case "Europe/Budapest": return "tzdb/europe-budapest.dat";
      case "Europe/Busingen": return "tzdb/europe-busingen.dat";
      case "Europe/Chisinau": return "tzdb/europe-chisinau.dat";
      case "Europe/Copenhagen": return "tzdb/europe-copenhagen.dat";
      case "Europe/Dublin": return "tzdb/europe-dublin.dat";
      case "Europe/Gibraltar": return "tzdb/europe-gibraltar.dat";
      case "Europe/Guernsey": return "tzdb/europe-guernsey.dat";
      case "Europe/Helsinki": return "tzdb/europe-helsinki.dat";
      case "Europe/Isle_of_Man": return "tzdb/europe-isle_of_man.dat";
      case "Europe/Istanbul": return "tzdb/europe-istanbul.dat";
      case "Europe/Jersey": return "tzdb/europe-jersey.dat";
      case "Europe/Kaliningrad": return "tzdb/europe-kaliningrad.dat";
      case "Europe/Kiev": return "tzdb/europe-kiev.dat";
      case "Europe/Kirov": return "tzdb/europe-kirov.dat";
      case "Europe/Lisbon": return "tzdb/europe-lisbon.dat";
      case "Europe/Ljubljana": return "tzdb/europe-ljubljana.dat";
      case "Europe/London": return "tzdb/europe-london.dat";
      case "Europe/Luxembourg": return "tzdb/europe-luxembourg.dat";
      case "Europe/Madrid": return "tzdb/europe-madrid.dat";
      case "Europe/Malta": return "tzdb/europe-malta.dat";
      case "Europe/Mariehamn": return "tzdb/europe-mariehamn.dat";
      case "Europe/Minsk": return "tzdb/europe-minsk.dat";
      case "Europe/Monaco": return "tzdb/europe-monaco.dat";
      case "Europe/Moscow": return "tzdb/europe-moscow.dat";
      case "Europe/Nicosia": return "tzdb/europe-nicosia.dat";
      case "Europe/Oslo": return "tzdb/europe-oslo.dat";
      case "Europe/Paris": return "tzdb/europe-paris.dat";
      case "Europe/Podgorica": return "tzdb/europe-podgorica.dat";
      case "Europe/Prague": return "tzdb/europe-prague.dat";
      case "Europe/Riga": return "tzdb/europe-riga.dat";
      case "Europe/Rome": return "tzdb/europe-rome.dat";
      case "Europe/Samara": return "tzdb/europe-samara.dat";
      case "Europe/San_Marino": return "tzdb/europe-san_marino.dat";
      case "Europe/Sarajevo": return "tzdb/europe-sarajevo.dat";
      case "Europe/Saratov": return "tzdb/europe-saratov.dat";
      case "Europe/Simferopol": return "tzdb/europe-simferopol.dat";
      case "Europe/Skopje": return "tzdb/europe-skopje.dat";
      case "Europe/Sofia": return "tzdb/europe-sofia.dat";
      case "Europe/Stockholm": return "tzdb/europe-stockholm.dat";
      case "Europe/Tallinn": return "tzdb/europe-tallinn.dat";
      case "Europe/Tirane": return "tzdb/europe-tirane.dat";
      case "Europe/Tiraspol": return "tzdb/europe-tiraspol.dat";
      case "Europe/Ulyanovsk": return "tzdb/europe-ulyanovsk.dat";
      case "Europe/Uzhgorod": return "tzdb/europe-uzhgorod.dat";
      case "Europe/Vaduz": return "tzdb/europe-vaduz.dat";
      case "Europe/Vatican": return "tzdb/europe-vatican.dat";
      case "Europe/Vienna": return "tzdb/europe-vienna.dat";
      case "Europe/Vilnius": return "tzdb/europe-vilnius.dat";
      case "Europe/Volgograd": return "tzdb/europe-volgograd.dat";
      case "Europe/Warsaw": return "tzdb/europe-warsaw.dat";
      case "Europe/Zagreb": return "tzdb/europe-zagreb.dat";
      case "Europe/Zaporozhye": return "tzdb/europe-zaporozhye.dat";
      case "Europe/Zurich": return "tzdb/europe-zurich.dat";
      case "GB": return "tzdb/gb.dat";
      case "GB-Eire": return "tzdb/gb-eire.dat";
      case "Greenwich": return "tzdb/greenwich.dat";
      case "HST": return "tzdb/hst.dat";
      case "Hongkong": return "tzdb/hongkong.dat";
      case "Iceland": return "tzdb/iceland.dat";
      case "Indian/Antananarivo": return "tzdb/indian-antananarivo.dat";
      case "Indian/Chagos": return "tzdb/indian-chagos.dat";
      case "Indian/Christmas": return "tzdb/indian-christmas.dat";
      case "Indian/Cocos": return "tzdb/indian-cocos.dat";
      case "Indian/Comoro": return "tzdb/indian-comoro.dat";
      case "Indian/Kerguelen": return "tzdb/indian-kerguelen.dat";
      case "Indian/Mahe": return "tzdb/indian-mahe.dat";
      case "Indian/Maldives": return "tzdb/indian-maldives.dat";
      case "Indian/Mauritius": return "tzdb/indian-mauritius.dat";
      case "Indian/Mayotte": return "tzdb/indian-mayotte.dat";
      case "Indian/Reunion": return "tzdb/indian-reunion.dat";
      case "Iran": return "tzdb/iran.dat";
      case "Israel": return "tzdb/israel.dat";
      case "Jamaica": return "tzdb/jamaica.dat";
      case "Japan": return "tzdb/japan.dat";
      case "Kwajalein": return "tzdb/kwajalein.dat";
      case "Libya": return "tzdb/libya.dat";
      case "MET": return "tzdb/met.dat";
      case "MST": return "tzdb/mst.dat";
      case "MST7MDT": return "tzdb/mst7mdt.dat";
      case "Mexico/BajaNorte": return "tzdb/mexico-bajanorte.dat";
      case "Mexico/BajaSur": return "tzdb/mexico-bajasur.dat";
      case "Mexico/General": return "tzdb/mexico-general.dat";
      case "NZ": return "tzdb/nz.dat";
      case "NZ-CHAT": return "tzdb/nz-chat.dat";
      case "Navajo": return "tzdb/navajo.dat";
      case "PRC": return "tzdb/prc.dat";
      case "PST8PDT": return "tzdb/pst8pdt.dat";
      case "Pacific/Apia": return "tzdb/pacific-apia.dat";
      case "Pacific/Auckland": return "tzdb/pacific-auckland.dat";
      case "Pacific/Bougainville": return "tzdb/pacific-bougainville.dat";
      case "Pacific/Chatham": return "tzdb/pacific-chatham.dat";
      case "Pacific/Chuuk": return "tzdb/pacific-chuuk.dat";
      case "Pacific/Easter": return "tzdb/pacific-easter.dat";
      case "Pacific/Efate": return "tzdb/pacific-efate.dat";
      case "Pacific/Enderbury": return "tzdb/pacific-enderbury.dat";
      case "Pacific/Fakaofo": return "tzdb/pacific-fakaofo.dat";
      case "Pacific/Fiji": return "tzdb/pacific-fiji.dat";
      case "Pacific/Funafuti": return "tzdb/pacific-funafuti.dat";
      case "Pacific/Galapagos": return "tzdb/pacific-galapagos.dat";
      case "Pacific/Gambier": return "tzdb/pacific-gambier.dat";
      case "Pacific/Guadalcanal": return "tzdb/pacific-guadalcanal.dat";
      case "Pacific/Guam": return "tzdb/pacific-guam.dat";
      case "Pacific/Honolulu": return "tzdb/pacific-honolulu.dat";
      case "Pacific/Johnston": return "tzdb/pacific-johnston.dat";
      case "Pacific/Kiritimati": return "tzdb/pacific-kiritimati.dat";
      case "Pacific/Kosrae": return "tzdb/pacific-kosrae.dat";
      case "Pacific/Kwajalein": return "tzdb/pacific-kwajalein.dat";
      case "Pacific/Majuro": return "tzdb/pacific-majuro.dat";
      case "Pacific/Marquesas": return "tzdb/pacific-marquesas.dat";
      case "Pacific/Midway": return "tzdb/pacific-midway.dat";
      case "Pacific/Nauru": return "tzdb/pacific-nauru.dat";
      case "Pacific/Niue": return "tzdb/pacific-niue.dat";
      case "Pacific/Norfolk": return "tzdb/pacific-norfolk.dat";
      case "Pacific/Noumea": return "tzdb/pacific-noumea.dat";
      case "Pacific/Pago_Pago": return "tzdb/pacific-pago_pago.dat";
      case "Pacific/Palau": return "tzdb/pacific-palau.dat";
      case "Pacific/Pitcairn": return "tzdb/pacific-pitcairn.dat";
      case "Pacific/Pohnpei": return "tzdb/pacific-pohnpei.dat";
      case "Pacific/Ponape": return "tzdb/pacific-ponape.dat";
      case "Pacific/Port_Moresby": return "tzdb/pacific-port_moresby.dat";
      case "Pacific/Rarotonga": return "tzdb/pacific-rarotonga.dat";
      case "Pacific/Saipan": return "tzdb/pacific-saipan.dat";
      case "Pacific/Samoa": return "tzdb/pacific-samoa.dat";
      case "Pacific/Tahiti": return "tzdb/pacific-tahiti.dat";
      case "Pacific/Tarawa": return "tzdb/pacific-tarawa.dat";
      case "Pacific/Tongatapu": return "tzdb/pacific-tongatapu.dat";
      case "Pacific/Truk": return "tzdb/pacific-truk.dat";
      case "Pacific/Wake": return "tzdb/pacific-wake.dat";
      case "Pacific/Wallis": return "tzdb/pacific-wallis.dat";
      case "Pacific/Yap": return "tzdb/pacific-yap.dat";
      case "Poland": return "tzdb/poland.dat";
      case "Portugal": return "tzdb/portugal.dat";
      case "ROC": return "tzdb/roc.dat";
      case "ROK": return "tzdb/rok.dat";
      case "Singapore": return "tzdb/singapore.dat";
      case "Turkey": return "tzdb/turkey.dat";
      case "UCT": return "tzdb/uct.dat";
      case "US/Alaska": return "tzdb/us-alaska.dat";
      case "US/Aleutian": return "tzdb/us-aleutian.dat";
      case "US/Arizona": return "tzdb/us-arizona.dat";
      case "US/Central": return "tzdb/us-central.dat";
      case "US/East-Indiana": return "tzdb/us-east-indiana.dat";
      case "US/Eastern": return "tzdb/us-eastern.dat";
      case "US/Hawaii": return "tzdb/us-hawaii.dat";
      case "US/Indiana-Starke": return "tzdb/us-indiana-starke.dat";
      case "US/Michigan": return "tzdb/us-michigan.dat";
      case "US/Mountain": return "tzdb/us-mountain.dat";
      case "US/Pacific": return "tzdb/us-pacific.dat";
      case "US/Samoa": return "tzdb/us-samoa.dat";
      case "Universal": return "tzdb/universal.dat";
      case "W-SU": return "tzdb/w-su.dat";
      case "WET": return "tzdb/wet.dat";
      case "Zulu": return "tzdb/zulu.dat";
      default: throw new IllegalArgumentException("Unknown zoneId: " + zoneId);
    }
  }
}
